version: 0.2

phases:
  install:
    commands:
      - Invoke-WebRequest -OutFile WebDeploy_amd64_en-US.msi https://download.microsoft.com/download/0/1/D/01DC28EA-638C-4A22-A57B-4CEF97755C6C/WebDeploy_amd64_en-US.msi
      - msiexec /i WebDeploy_amd64_en-US.msi /quiet
      - Start-Sleep 30
  pre_build:
    commands:
      - nuget restore
  build:
    commands:
      - msbuild /P:Configuration=Release /T:Build
      - msbuild SampleWebAPI/SampleWebAPI.csproj /P:Configuration=Release /T:Package
      - dotnet test SampleWebAPITests/SampleWebAPITests.csproj
      - cp appspec.yml SampleWebAPI\obj\Release\Package\appspec.yml
artifacts:
  files:
    - '**/*'
  base-directory: 'SampleWebAPI\obj\Release\Package'
